### ISSUE TITLE
command: add 'copy revision path' and 'copy revision path (workspace)' 

### ISSUE THREAD

**Issue by kaiyue0329** [vince-fugnitto/local-history-ext#104]
~Add a command called `Reveal Revision Folder in Finder`, which opens the revision folder in the OS explorer for the active editor.~

Since we cannot successfully invoke the operating system finder (limitation from the browser), the next best alternative would be to introduce two new commands which end-users can use to easily locate their revisions:

1. `copy revision path`: adds the revision path (active editor) to the clipboard
2. `copy revision path (workspace)`: adds the revision path (the given workspace) to the clipboard

End-users can then use these values in their terminal or finder to easily locate the revisions.

**Comment by vince-fugnitto** [comment]
@kaiyue0329 I'm thinking we should have two commands:
1. ability to open the finder at the current editor under `.local-history` (ex: 'readme.md')
2. ability to open the finder at the current workspace under `.local-history` (ex: 'theia')
