### ISSUE TITLE
Bugs when using the extension in Theia

### ISSUE THREAD

**Issue by Anasshahidd21** [vince-fugnitto/local-history-ext#124]
Bug#1: 
Preference `Exclude Files` does not work. When a file matching the glob pattern is saved, it results in saving the files and creating revisions for it. The ideal case would have been to ignore the files from creating revisions that match the glob. 

Bug#2: 
`Local History: View History` when triggered always displays `No local history found for (filename)` and it logs an error in the output channel, stating: `[Warning - 02:37:11:3711]: Error: 'No available file system provider for schema file`

Bug#3:
The output channel is flooded with such errors when active editors are changed. 
![tst](https://user-images.githubusercontent.com/43870550/84073038-17f3c500-a99e-11ea-8eda-e322000ad58b.PNG)

Bug#4:
When saving the active editor(on Linux) no new revisions are created. 

**How to Reproduce:**
Bug#1:
- Go to preference > Local History > Exclude files 
- In the `settings.json`  , add `"**/.txt" : true` in the excludeFile settings
- Create a new `.txt` file and check to see if saving it creates new revisions or not. 

Bug#2:
- On a file with revisions, try triggering `f1` `Local History: View History` and test to see if the history files are displayed. 

Bug#3: 
- Have 2 active editors, and open the `Output` channel to `Local History` test to see if the above-mentioned errors show up in the channel  

Bug#4:
- Erase any previous `~/.local-history` folder and try saving a new file to see if the revision file is created.

**Comment by vince-fugnitto** [comment]
I created the corresponding issues so they can be tracked and worked on easily.
#125, #126, #127 

We can see if the 3rd bug is resolved by fixing the other issues (namely being able to actually save revisions).
