### ISSUE TITLE
bug: 'exclude files' preference does not work correctly

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#127]
**Description**

The preference `local-history.excludeFile` does not work properly (it continues to save files that match the glob).

**Steps to Reproduce**

1. Go to preference > Local History > Exclude files
2. In the `settings.json` , add `"**/.txt" : true` in the `excludeFile` settings
3. Create a new `.txt` file and check to see if saving it creates new revisions or not

**Comment by vince-fugnitto** [comment]
@Anasshahidd21 your glob is incorrect, the correct value would be:

```json
"**/*.txt": true
```

In your case you are excluding all files that are named `.txt`

**Comment by Anasshahidd21** [comment]
> @Anasshahidd21 your glob is incorrect, the correct value would be:
> 
> ```json
> "**/*.txt": true
> ```
> 
> In your case you are excluding all files that are named `.txt`

Yes you are right, it works well with the updated glob.
