### ISSUE TITLE
bug: icons are not displayed correctly

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#129]
**Description**

The `Local-History: Tree View` widget does not display the icons properly.
The icons for `refresh` and the `remove` (trash) are not displayed in both the browser and electron.

**Comment by Anasshahidd21** [comment]
![ok](https://user-images.githubusercontent.com/43870550/84162219-21346e80-aa3e-11ea-93e8-87d11805fe1e.png)
the icons for `revert` and `remove revision` are not displayed, when hovered over them, they seem to exist but does not respond to click events.
