### ISSUE TITLE
Commands are not visible

### ISSUE THREAD

**Issue by Anasshahidd21** [vince-fugnitto/local-history-ext#132]
![image](https://user-images.githubusercontent.com/43870550/84163579-a4a28f80-aa3f-11ea-974d-8167c41eccb3.png)

I have noticed, once we perform a `Local History: Clear Revisions`, we no longer see the Local History commands like `Local History: View Revisions`, however, once there is a new save performed(new revision is created) the commands reappear back again. 
Was this a design decision by us?

**Comment by vince-fugnitto** [comment]
@Anasshahidd21 can you retest the latest `master`, I tried recently and it seemed to work fine.

**Comment by Anasshahidd21** [comment]
the issue doesn't seem to exist in the latest master.
