### ISSUE TITLE
bug: remove toolbar items to diff editor

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#133]
**Description**

For simplicity, we should remove the toolbar item commands when viewing in a diff editor since they are problematic and do not work well.

For example, the following `when` condition is problematic as it will display the `revert` when in a normal scm diff editor as well:

https://github.com/vince-fugnitto/local-history-ext/blob/cf3930f2ccb55bbcdc42195f0db80b263d170631/package.json#L49

Perhaps we can simplify it to perform such operations only from the `tree-view`.

What do you guys think? cc @kaiyue0329 @Anasshahidd21

**Comment by Anasshahidd21** [comment]
I like the approach, we can also do it the way we did at the beginning, ie: to have a command for `revert` the way we have it for `View History`.

**Comment by kaiyue0329** [comment]
I like this approach as well. I thikn it would be more straightforward for users to perform `revert` and `delete` operations only from the tree-view.

**Comment by vince-fugnitto** [comment]
> I like this approach as well. I thikn it would be more straightforward for users to perform `revert` and `delete` operations only from the tree-view.

@kaiyue0329 I believe it is possible to contribute a context-menu directly to the tree-view to have these operations, it would clutter the `toolbar` less (ex: when we have gitlens installed) and would be self-contained to the view. Do you mind taking care of it?

**Comment by kaiyue0329** [comment]
> > I like this approach as well. I thikn it would be more straightforward for users to perform `revert` and `delete` operations only from the tree-view.
> 
> @kaiyue0329 I believe it is possible to contribute a context-menu directly to the tree-view to have these operations, it would clutter the `toolbar` less (ex: when we have gitlens installed) and would be self-contained to the view. Do you mind taking care of it?

@vince-fugnitto Sure. I will create a PR for it.
