### ISSUE TITLE
Saving without updating content, doesn't rename the file.

### ISSUE THREAD

**Issue by Anasshahidd21** [vince-fugnitto/local-history-ext#134]
When saved without changing the content, the latest revision file name is not updated. 

**How to Test:**
1. Create a revision
2. Without making any changes, save again. 
3. Check to see if the file name is renamed.

**Comment by vince-fugnitto** [comment]
Instead, we should remove the functionality which simply updates the timestamp without any changes.
This will clean up the code and will not expose the difference in behavior between Theia and VS Code.
