### ISSUE TITLE
[question] Documentation: add info about revision context metadata

### ISSUE THREAD

**Issue by kaiyue0329** [vince-fugnitto/local-history-ext#145]
Should we add information about [revision context metadata](https://github.com/vince-fugnitto/local-history-ext/issues/74#issuecomment-627954066) in the filename (revert change `_r`, manual change `_m`) to the documentation?

cc @vince-fugnitto @Anasshahidd21

**Comment by vince-fugnitto** [comment]
@kaiyue0329 sounds good, you can mention it so users know the difference between these two types of revisions.
