### ISSUE TITLE
local-history: add explorer context menu to trigger history for selected file

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#15]
**Description**

It should be possible to trigger the **local history** for a given file (selection), in the explorer's context menu. Triggering this command should execute the quick-open to see the list of entries.

**Comment by kaiyue0329** [comment]
@vince-fugnitto I believe this feature is already implemented in Story 1:
> * trigger the local history for a given file in the explorer's context menu
