### ISSUE TITLE
Local-history: "empty" sub menu item should be present or not 

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#150]
**Description**
In local history view, the sub-menu has "Empty" field, should we have some menu items or nothing ?

**Checklist**

**Additional Information**
![EmptySubMenu](https://user-images.githubusercontent.com/419051/84695351-b3de7d00-af18-11ea-9022-7ecdb48ebf68.gif)

**Comment by vince-fugnitto** [comment]
@kaiyue0329 do you mind taking care of the issue? It's possible that Theia does not properly handle context-menu which are empty so we could fix the issue by adding the same inline actions to the context-menu as well.

**Comment by kaiyue0329** [comment]
> @kaiyue0329 do you mind taking care of the issue? It's possible that Theia does not properly handle context-menu which are empty so we could fix the issue by adding the same inline actions to the context-menu as well.

@vince-fugnitto Sure! I will create a PR for it.
