### ISSUE TITLE
Delete option in local-history doesn't seem to delete the local-history file

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#151]
**Description**
Using the delete option in the local history 
- remove the file in the editor
- Generate errors on the console
- Initiate an nsfw "started watching" for the file and the local history file

If I re-open the file in  the editor, the deleted file in local history re-appears in the local-history view

Should the file be deleted ? 
**Checklist**

**Additional Information**
![LocalHistoryDelete](https://user-images.githubusercontent.com/419051/84697046-6f081580-af1b-11ea-981d-c27a65eec23d.gif)

**Comment by vince-fugnitto** [comment]
@lmcbout on the actual filesystem, is the file deleted? (that is the scope of the command, `nsfw` watching is specific to Theia and is not controlled by the extension).

**Comment by lmcbout** [comment]
@vince-fugnitto Why the nsfw :STARTING" after I selected the delete option, nsfw should "STOP" at that time, not START

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Why the nsfw :STARTING" after I selected the delete option, nsfw should "STOP" at that time, not START

It has nothing to do with this extension.
The extension does not control or call `nsfw` in any way (ex: we do not explicit create a watcher in the extension).
