### ISSUE TITLE
Should we warn the end-user when he reaches the file size limit for the local-history!

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#152]
**Description**
When we reach the file size limit, should we put a warning in the local-history view to indicate there is no more new file being created since the file size limit is reached?

- Being picky: 1Mb = 1024 bytes,  not 1000 bytes :)
When I look at the preference "History File Size Limit",  Controls the maximum acceptable file size for storing revisions in **megabytes**. So 5Mb is not 5000000 but 5242880 bytes (5 * 2 power10)

**Checklist**

**Additional Information**

**Comment by vince-fugnitto** [comment]
@Anasshahidd21 can you open a pull-request to log when we do not save due to a file size limit? I don’t think notifications would be appropriate as they would be too noisy to end-users.

**Comment by Anasshahidd21** [comment]
@vince-fugnitto sure I’ll get it done.
