### ISSUE TITLE
question: should we limit local history only to files outside of '.local-history'

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#16]
**Description**

At the moment, it is possible to make changes to a file present under `.local-history` which consequently creates a new revision. Should we instead limit the creation of local-history files outside of the `.local-history' folder. Ideally, such a folder would remain readonly.

**Comment by marcdumais-work** [comment]
Where is `.local-history` saved? I think in the workspace? If so do we have a way yet to avoid it interfering with the workspace? e.g. the contained files showing-up as untracked files for `git`? 

Is there a VS Code API that permits programmatically adding files/folders to some "excluded" list that would be respected by `git` (and potentially this extension as well)?

**Comment by vince-fugnitto** [comment]
> Where is `.local-history` saved? I think in the workspace? If so do we have a way yet to avoid it interfering with the workspace? e.g. the contained files showing-up as untracked files for `git`?
> 
> Is there a VS Code API that permits programmatically adding files/folders to some "excluded" list that would be respected by `git` (and potentially this extension as well)?

The `.local-history` folder is saved in the workspace at the moment. 
There exists the following preference which limits the visibility of files in the `explorer` so perhaps we can create our own preference which extends this one to not apply the local-history for the exclude list:

<img width="787" alt="Screen Shot 2020-04-17 at 10 27 20 AM" src="https://user-images.githubusercontent.com/40359487/79579897-345a3c00-8096-11ea-9f45-bdf6e9d221c0.png">

**Comment by vince-fugnitto** [comment]
At least with using the mechanism of `files.exclude` users can control which files/folders they want to exclude from the local-history behavior, and by default we can include the `.local-history` folder.

**Comment by marcdumais-work** [comment]
Now that we have a nicer way to deal with VS Code extensions (unpack them under `~/.productName/extensions`) we could consider saving the local file history under there as well and avoid this problem completely. 

In fact, if the extension creates files/folders without mentioning an absolute path I assume they will be created under the unzipped extension, with root folder being probably the `~/.productName/extensions/<extension name>/extension/` folder. We could add one directory to reflect which workspace this is from, so there is no clash between different workspaces. 

WDYT?

One potential downside is that if the user moves the workspace on the filesystem, the path where we save the history might change as well and old local history may not be found automatically by the extension.

**Comment by vince-fugnitto** [comment]
I'm not sure if we should rely on where the plugins are saved as we want to be agnostic to both theia-applications and vscode ones. Controlling the behavior as a preference such as `localHistory.excludes` can offer more flexibility to end-users.

**Comment by marcdumais-work** [comment]
> Controlling the behavior as a preference such as `localHistory.excludes` can offer more flexibility to end-users.

We could  exclude `.local-history/*` by default in this preference and perhaps also automatically exclude whatever is in the project's `.gitignore`. 

The part that I think may not work so well is to automatically exclude the content of `.local-history/` for `git`, so that the backed-up files do no show-up as untracked files or be committed by accident. I am not a fan of asking the user to add this in their project's `.gitignore`.
