### ISSUE TITLE
 Preference field "local-history.fileSizeLimit " needs a default or a minimal  value

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#160]
**Bug Description**
If the value for  "local-history.fileSizeLimit " is not set in the workspace preferences, modifying a file result in:
[Info - 02:37:07:377]: No new revisions created for file 'settings.json'. The file exceeds the local history file size limit (0Mb).

There should be a minimum or at least a default value for the field

**Steps to Reproduce**
- Open the preference page
- Select the workspace tab
- Remove the setting for the value  "local-history.fileSizeLimit " (it is undefined at this point
- Modify anty other preference value
-->  [Info - 02:38:05:385]: No new revisions created for file 'settings.json'. The file exceeds the local history file size limit (0Mb).

**Comment by vince-fugnitto** [comment]
@lmcbout 

There is a default and minimum value for such a preference:

https://github.com/vince-fugnitto/local-history-ext/blob/766af8864f8fc0ead93a2b6b40499b99751ef465/package.json#L199-L204

It is up to Theia to validate it and fallback to the default value if a preference is not set correctly.

For example, in VS Code:
<div align='center'>

![Screenshot from 2020-06-16 14-46-49](https://user-images.githubusercontent.com/40359487/84814952-46961f00-afe0-11ea-843d-4908c621a67d.png)


</div>

**Comment by vince-fugnitto** [comment]
Here is the corresponding Theia issue: https://github.com/eclipse-theia/theia/issues/7741

**Comment by vince-fugnitto** [comment]
We can update our service to fallback to the `default` value if we ever have an incorrect preference:
- `min` violation
- `type` violation

cc @Anasshahidd21
