### ISSUE TITLE
New traces on the console since I used local-history 0.0.3 

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#166]
**Bug Description**
Using local-history versio 0.0.3
The first time I open the explorer view (Focus was in SCM view initially), the following trace appears on the console.log
```
root INFO [hosted-plugin: 27474] 1
root INFO [hosted-plugin: 27474] 1
....
```

**Steps to Reproduce**
- Clone the git branch having the local-history + compile
- Start Teal  with local-history version 0.0.3
- Put the focus on the Explorer view (Was on SCM view when stated)
--> The traces appear  the first times the focus is on the explorer view

**Comment by vince-fugnitto** [comment]
The logs occur without the extension as well (standard Theia).
For instance, you can search for any `console.log` by this extension and you will notice none.
