### ISSUE TITLE
NSFW start multiple times with latest configuration

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#167]
**Bug Description**
In TEAL, nsfw start multiple times when it only start once in Theia latest master (commit d58d1bac09b7a7a8f6c9eaab3456cf26cb0fd05f ). Is it because of the local-history view?

```
root INFO [nsfw-watcher: 27436] Started watching: /home/lmcbout/theia/theia/packages/callhierarchy/src/browser/callhierarchy-context.ts
root INFO [nsfw-watcher: 27436] Started watching: /home/lmcbout/theia/theia/packages/callhierarchy/src/browser/callhierarchy-context.ts
root INFO [nsfw-watcher: 27436] Stopped watching: /home/lmcbout/theia/theia/packages/callhierarchy/src/browser/callhierarchy-context.ts
root INFO [nsfw-watcher: 27436] Started watching: /home/lmcbout/theia/theia/packages/callhierarchy/src/browser/callhierarchy-context.ts
root INFO [nsfw-watcher: 27436] Stopped watching: /home/lmcbout/theia/theia/packages/callhierarchy/src/browser/callhierarchy-context.ts

```

**Steps to Reproduce**
Start TEAL
- Open any files
--> nsfw "start/stop" multiple times instead of just starting one

**Comment by vince-fugnitto** [comment]
@lmcbout as mentioned before, the extension does not explicitly create watchers, it is theia itself that handles such code and if there is an update to be made it is not this extension so I'm not sure why you describe it as a `bug`.
