### ISSUE TITLE
local-history: add command to clear local history

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#28]
**Description**

As a user, it should be possible to perform the following utility actions for cleanup:
- **Clear Local History (Active File)**: clears the local history for the active editor
~~**Clear Local History**: clears entire local history for the given workspace.~~

Both commands should require confirmation by end-users before actually completing.

**Comment by kaiyue0329** [comment]
@vince-fugnitto Would the two commands be in both the editor context menu and the Command Palette?

**Comment by kaiyue0329** [comment]
@vince-fugnitto Would the two commands be in both the editor context menu and the Command Palette?
