### ISSUE TITLE
local-history: listen to changes to '.local-history'

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#32]
**Description**

Currently, the only time we load entries from `.local-history` is when we first load a workspace, or the workspace has been updated (changed workspace). We should also listen to changes made the `.local-history` folder such as deletions to properly update the internal `historyFiles`:

https://github.com/vince-fugnitto/local-history-ext/blob/master/src/local-history/local-history-manager.ts#L15

Currently, if a user deletes the `.local-history` when it previously had entries, triggering the `viewAllForActiveEditor` will display stale results.

**Steps to Reproduce**

1. open a workspace
2. open a file (ex: 'a.ts')
3. make arbitrary saves to the file (creating local-history revisions)
4. trigger the local-history for the file (should properly display results)
5. delete the `.local-history` folder manually
6. trigger the local-history for the file - it should not display anything but instead displays stale results

**Comment by kaiyue0329** [comment]
This issue no longer exists. Entries are now reloaded each time when we view local history for an active editor.
