### ISSUE TITLE
[Bug]: For Windows, file is removed but is not updated in the quick pick. 

### ISSUE THREAD

**Issue by Anasshahidd21** [vince-fugnitto/local-history-ext#40]
**Description**
Currently in master, when we try to save a new revision of the file. A notification is displayed saying the file is removed successfully, but it still appears when seen in `Local History: Active Editor` 

![Untitled](https://user-images.githubusercontent.com/43870550/80635355-c6186080-8a29-11ea-9fe6-c93775c1058b.png)

How to Reproduce: 
1. Open a file, make couple of revisions
2. Press `f1` and search for `Local History: Active Editor` 
3. Open a previous revision
4. Delete a previous revision using the trash can icon
5. Repeat step 2 and the file still exists in the quick pick menu
6. When file is opened, an error is displayed.

**Additional Information**
This issue occurred on Windows 10 with me.

**Comment by kaiyue0329** [comment]
I was able to reproduce this issue on Windows 8 as well. I noticed that I was only able to delete the revisions created in the previous `Extension Development Host` session. After deletion, the deleted revisions did not show up in the quickPick menu. 

When trying to delete the revisions created in the current `Extension Development Host`, the error occurred.
