### ISSUE TITLE
preference: add a preference to control the number of entries to keep for a file

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#5]
**Description**

Add a new preference to control the number of entries to keep for a given file.
Something like: `localHistory.maxEntriesPerFile` which defaults to 10.

**Comment by kaiyue0329** [comment]
@vince-fugnitto If there are 10 copies for file `abc.ts` and we update `localHistory.maxEntriesPerFile` to 5, do we only keep 5 latest revisions of `abc.ts`?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto If 10 revisions are saved for file `abc.ts` and we update `localHistory.maxEntriesPerFile` to 5, do we only keep 5 latest revisions of `abc.ts`?

For the case where the we already had 10 entries, and a user updates it to 5 max, I think it should only apply to us listing the 5 most recent. We should warn users that older entries are present and that they should perform a cleanup. I don't think we should do a cleanup ourselves (let's say in the case it's 10 to 5 and 10 again we dont want the user to have lost entries).
