### ISSUE TITLE
handle history when file is deleted

### ISSUE THREAD

**Issue by Anasshahidd21** [vince-fugnitto/local-history-ext#53]
If a file has past history, and we delete the file. We should prompt the user if they want to keep the local history of the file or get rid of it 

**How to Reproduce**
1. Open a workspace
2. Open a file, create multiple revisions
3. Delete the file.
4. The local history for that file exists.

**Comment by vince-fugnitto** [comment]
I don't think this is applicable in the first iteration of the pull-request.
The deleted file will be backed-up and it will be up to users to determine what to do with the revisions manually. I'll close it for now.
