### ISSUE TITLE
proposal: create a local-history tree-view view-container

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/local-history-ext#60]
**Description**

What do you guys think of adding a [`TreeView`](https://code.visualstudio.com/api/extension-guides/tree-view) container contribution for **local-history**. I was thinking that based on the active editor, we can list the revisions in this container for users to view more easily:

- https://code.visualstudio.com/api/extension-guides/tree-view#view-container

This will essentially add a new view (or widget) to the sidebar:

<img width="602" alt="Screen Shot 2020-05-07 at 10 40 52 AM" src="https://user-images.githubusercontent.com/40359487/81307977-41dc6380-904f-11ea-888e-55668962ee0d.png">

**Functionality**

- [x] view the local-history for the active file
- [x] upon clicking the entries, the diff is opened
- [x] possibility to remove entries directly from the view
- [ ] (optional) possibility to view +/- of the revision

**Comment by kaiyue0329** [comment]
@vince-fugnitto I think it's a great idea!

**Comment by Anasshahidd21** [comment]
In the view container, we can also have a contribution for something like `History from the past hour/week` just to give more access to the user. wdyt? @kaiyue0329 @vince-fugnitto

**Comment by kaiyue0329** [comment]
> In the view container, we can also have a contribution for something like `History from the past hour/week` just to give more access to the user. wdyt? @kaiyue0329 @vince-fugnitto

I think we can have two categories: `within two weeks` and `older than two weeks`. The user can see a more detailed relative time in the quickPick Menu. Or we can even have the relative time as part of the tree node.

**Comment by vince-fugnitto** [comment]
> In the view container, we can also have a contribution for something like `History from the past hour/week` just to give more access to the user. wdyt? @kaiyue0329 @vince-fugnitto

I don't think it is easily doable and will require too much complexity and management.
It is not easy to determine for a given workspace which files are associated to it from the `.local-history` folder without traversing all revisions.

**Comment by Anasshahidd21** [comment]
> I don't think it is easily doable and will require too much complexity and management.
> It is not easy to determine for a given workspace which files are associated to it from the `.local-history` folder without traversing all revisions.

I think what I was proposing was based on the active file. 

let's say if we have  a.ts opened, it will show the history files within the last hour/week for that file only.

**Comment by vince-fugnitto** [comment]
> > I don't think it is easily doable and will require too much complexity and management.
> > It is not easy to determine for a given workspace which files are associated to it from the `.local-history` folder without traversing all revisions.
> 
> I think what I was proposing was based on the active file.
> 
> let's say if we have a.ts opened, it will show the history files within the last hour/week for that file only.

@Anasshahidd21 
I don't think it's useful?
Displaying all the revisions of the file (sorted by newest) would achieve the same thing.
