### ISSUE TITLE
save history when file is closed. 

### ISSUE THREAD

**Issue by Anasshahidd21** [vince-fugnitto/local-history-ext#62]
We should perform a save when the user closes a file.

**Comment by kaiyue0329** [comment]
@Anasshahidd21 If a file is dirty, the OS would ask the user to save/discard the changes. If the changes are saved, we will create a revision (since we listen to `onDidSaveTextDocument` event).

**Comment by vince-fugnitto** [comment]
> @Anasshahidd21 If a file is dirty, the OS would ask the user to save/discard the changes. If the changes are saved, we will create a revision (since we listen to `onDidSaveTextDocument` event).

@kaiyue0329 the idea is to update the last revision's timestamp when closing a document (get the most recent update of a file). You are right about the handling of the other cases, but in general it is to update the last revision when closing a document.
