### ISSUE TITLE
preferences: Prevent user from violating the min/max values

### ISSUE THREAD

**Issue by kaiyue0329** [vince-fugnitto/local-history-ext#72]
**Description**
We should declare a max and a min (greater or equal than 0) for each preference. We can use if conditions and reminders in the ext Settings to prevent the user from violating the min/max values.

**Comment by vince-fugnitto** [comment]
@kaiyue0329 we can simply update the schema (present in the `package.json`) for such preferences to also include `minimum` and `maximum` values. This will ultimately:
- protect against setting invalid preference values (for numbers)
- provide users with instant feedback in the preferences-view with input validation
- provide users with feedback when manually editing the `settings.json` file (problem markers)
- if an invalid value is provided, the default will be used instead


_Additional Info_: [contribution.configuration docs](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration)

<div align='center'>

<img width="754" alt="Screen Shot 2020-05-12 at 9 07 14 AM" src="https://user-images.githubusercontent.com/40359487/81694987-061b1280-9430-11ea-99c4-c140cc05e918.png">

</div>
