### ISSUE TITLE
Save current file just before reverting

### ISSUE THREAD

**Issue by Anasshahidd21** [vince-fugnitto/local-history-ext#74]
Since the user can revert back to the previous state of the file by accident, we should save the current state of the file (before the reversion happens) as a revision.

**Comment by kaiyue0329** [comment]
@vince-fugnitto @Anasshahidd21 For this issue, do we want to create new revision or overwrite the most recent revision?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto @Anasshahidd21 For this issue, do we want to create new revision or overwrite the most recent revision?

I think the simplest thing to do would be to create a new revision. We want the state before we perform a revision especially if new changes were made. This way users can still see the history of the file before they decided to revert.

**Comment by Anasshahidd21** [comment]
> @vince-fugnitto @Anasshahidd21 For this issue, do we want to create new revision or overwrite the most recent revision?

If the contents are not changed, then we can overwrite else create a new history. there isn't any point in having redundant copies, imo.

**Comment by vince-fugnitto** [comment]
> > @vince-fugnitto @Anasshahidd21 For this issue, do we want to create new revision or overwrite the most recent revision?
> 
> If the contents are not changed, then we can overwrite else create a new history. there isn't any point in having redundant copies, imo.

My original idea was to save it always (even if the contents were not updated) so we have a clean copy before a revert was made, but I was also thinking of marking this revision especially somehow to reflect that it was created before a **revert** was made. At the moment we don't have any metadata associated with our revisions, but I am wondering if end-users will appreciate knowing some context of revisions for example:
- manual change
- revert change

It might be overkill at the moment so the simplest approach should be best.
