### ISSUE TITLE
changing preference and performing save, creates a history for it too. 

### ISSUE THREAD

**Issue by Anasshahidd21** [vince-fugnitto/local-history-ext#79]
Currently, if we try to change a preference, and perform a save on it, it will change the preference setting as a revision as well. 
since we don't display the `Local History: Active Editor` for sources which are not of resourceType as `file`, there is no point in storing the  history for it too. 

Reproductive Steps: 
1. open settings> preferences 
2. change a preference value and perform a manual save
3. check to see in filesystem, it must have created a new revision on that 
![03](https://user-images.githubusercontent.com/43870550/81846189-b1ef5b80-951f-11ea-9ef9-2fb7b131866e.PNG)

**Comment by vince-fugnitto** [comment]
@Anasshahidd21 is it an issue to save a revision of the preferences? (it is like any file)

**Comment by Anasshahidd21** [comment]
> @Anasshahidd21 is it an issue to save a revision of the preferences? (it is like any file)

I don't find the point of it, when we don't display the `Local History: Active Editor` when the active editor is the `preferences`.

```
                {
                    "command": "local-history.viewHistory",
                    "when": "editorIsOpen && resourceScheme == file"
                }
```

The resource scheme for preferences doesn't seem to be a file.

**Comment by vince-fugnitto** [comment]
> > @Anasshahidd21 is it an issue to save a revision of the preferences? (it is like any file)
> 
> I don't find the point of it, when we don't display the `Local History: Active Editor` when the active editor is the `preferences`.

We can open the `settings.json` as a standard JSON file so I don't see why not.
